[package]
name = "rusty-vm"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "3.0.0"
tokio = { version = "1.47.1", features = ["full"] }
gpu = { version = "0.1.0", path = "gpu" }
macroquad = "0.4.14"

[workspace]
members = [
    "gpu",
    "rvmasm",
]

